name: Continuous Delivery

on:
  release:
    types:
      - published

  workflow_dispatch:


jobs:
    
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - id: install-secret-key
      name: Install gpg secret key
      run: |
        cat <(echo -e "${{ secrets.OSSRH_GPG_SECRET_KEY }}") | gpg --batch --import
        gpg --list-secret-keys --keyid-format LONG
    - name: Set up JDK
      uses: actions/setup-java@v1
      env:
        MAVEN_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
      with:
        java-version: 1.8
        server-id: ossrh
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
        gpg-private-key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
        gpg-passphrase: MAVEN_GPG_PASSPHRASE
        
    - name: Publish to the Maven Central Repository
      env:
        MAVEN_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
      run: |
        ./mvnw \
          -P ossrh \
          --no-transfer-progress \
          --batch-mode \
          clean deploy
