name: Continuous Delivery (snapshot)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:


jobs:
    
  publish:
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'

    steps:
    - uses: actions/checkout@v2
    - id: install-secret-key
      name: Install gpg secret key
      run: |
        cat <(echo -e "${{ secrets.OSSRH_GPG_SECRET_KEY }}") | gpg --batch --import
        gpg --list-secret-keys --keyid-format LONG
    - name: debug
      run: ls -al /home/runner/.gnupg

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: 8
        distribution: zulu

    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

    - name: Publish to the Maven Central Repository
      env:
        ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.SONATYPE_USERNAME }}
        ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.SONATYPE_PASSWORD }}
      run: |
          ./gradlew -Ptarget=snapshot \
            -Psigning.gnupg.executable=gpg2 \
            -Psigning.gnupg.keyName=${{secrets.OSSRH_GPG_SECRET_KEY_ID }} \
            -Psigning.gnupg.passphrase=${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }} \
            clean publishToSonatype
